In [1]:
import torch

In [2]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 1.8600,  0.5754, -0.3699], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([3.8600, 2.5754, 1.6301], grad_fn=<AddBackward0>)


In [4]:
z = x - 2
print(z)

tensor([-0.1400, -1.4246, -2.3699], grad_fn=<SubBackward0>)


In [5]:
s = y*y*3
print(s)

tensor([44.6988, 19.8983,  7.9718], grad_fn=<MulBackward0>)
